# arguments spec file for redhat.ocp.ci_artifacts_download role
---
argument_specs:
  main:
    short_description: redhat.ocp.ci_artifacts_download
    description:
      - This is the main entrypoint for the redhat.ocp.ci_artifacts_download role.
      - It downloads last `jobs` of ci jobs of type `job_type` and unpacks them.
    author:
      - Max Kovgan
    options:
      cad_jobs_map:
        type: "dict"
        required: true
        description:
          - The map of ci_artifacts_downloader configuration.
      cad_job_profile:
        type: "str"
        default: "functional-tests"
        required: false
        description:
          - Team profile, determines which cad_jobs_map configuration key to use
      cad_target_path:
        type: "str"
        required: false
        default: "{{ playbook_dir }}/{{ role_name }}/downloads"
        description:
          - Where to download jobs' archives
      cad_last_builds:
        type: "int"
        default: 10
        required: false
        description:
          - How many job last builds artifacts to download
