# SPDX-License-Identifier: Apache-2.0
---
# meta file for redhatci.ocp.report_send

galaxy_info:
  author: Red Hat CI
  description: Role to send pre-combined event data to collectors
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "37"
        - "38"
        - "39"
  galaxy_tags:
    - testing
    - reporting
    - splunk
    - ci
    - transmission

dependencies: []

argument_specs:
  main:
    short_description: Send pre-combined event data to collectors
    description: |
      This role sends pre-combined event data to supported collectors.
      It handles authentication, data validation, and transmission.
      Input should be a JSON file with the event already formatted for the target collector.
    options:
      rs_combined_event_path:
        description: Path to the pre-combined event JSON file
        type: str
        required: true
      rs_collector_url:
        description: URL of the collector server
        type: str
        required: true
      rs_collector_auth_token:
        description: Authentication token for the collector
        type: str
        required: false
        default: ""
      rs_collector_target:
        description: Collector target/channel/topic identifier
        type: str
        required: false
        default: ""
      rs_collector_source:
        description: Override source in event payload
        type: str
        required: false
        default: ""
      rs_collector:
        description: Type of collector to use
        type: str
        required: false
        default: "splunk"
        choices: ["splunk"]
      rs_do_send:
        description: Whether to actually send the data
        type: bool
        required: false
        default: true
