---
# SPDX-License-Identifier: Apache-2.0
# this task list downloads artifacts for role redhatci.ocp.ci_artifacts_download

- name: Ensure builds artifacts containing folder
  ansible.builtin.file:
    path: "{{ cad_download_root }}"
    state: directory
    mode: '0755'


# occasionally there are these:
# (
#   item={
#     '_class': 'org.jenkinsci.plugins.workflow.job.WorkflowRun',
#     'number': 65,
#     'url': 'https://jenkins-server.domain.com/view/View1/job/Job/job/cool-compute-4.18/65/'
#   }
# ) => {
#   "ansible_loop_var": "build_info",
#   "build_info": {
#     "_class": "org.jenkinsci.plugins.workflow.job.WorkflowRun",
#     "number": 65,
#     'url': 'https://jenkins-server.domain.com/view/View1/job/Job/job/cool-compute-4.18/65/'
#   },
#   "changed": false,
#   "elapsed": 0,
#   "msg": "failed to create temporary content file: The read operation timed out"
# }

- name: Download builds artifacts
  ansible.builtin.get_url:
    url: "{{ build_info.url }}artifact/*zip*/{{ build_info.url | urlsplit('path') | regex_replace('^/|/$', '') | replace('/', '-') }}.zip"
    validate_certs: false
    # user: "{{ cad_username }}"
    # password: "{{ cad_token }}"
    # force_basic_auth: true
    # headers:
    #   Content-Type: application/x-www-form-urlencoded
    dest: "{{ cad_download_root }}"
    timeout: "{{ cad_timeout }}"
    unsafe_writes: true
    mode: '0644'
  register: get_url_results
  loop: "{{ builds_info.json.builds }}"
  loop_control:
    loop_var: build_info
  retries: 3
  delay: 2
