# SPDX-License-Identifier: Apache-2.0
---
# tasks file for role redhatci.ocp.ci_artifacts_download

- name: Validate variables have loaded properly from vars file
  ansible.builtin.assert:
    that: "{{ condition }}"
    msg: "Mandatory variable is missing/empty, refer to the log messages"
  loop:
    - (cad_config_profile is defined) and (cad_config_profile | length > 0)
    - (global_ci_server_url is defined) and (global_ci_server_url | length > 0)
    - (global_ci_type is defined) and (global_ci_type in ["jenkins"])
    - (global_last_builds is defined) and (global_last_builds | length > 0)
  loop_control:
    loop_var: condition

- name: Validate global_ci_type
  ansible.builtin.assert:
    that: "{{ condition }}"
  loop_control:
    loop_var: condition
  loop:
    - global_ci_type in ["jenkins", "dci"]


- name: "Get artifacts of jobs from {{ global_ci_type }}"
  ansible.builtin.include_tasks:
    file: "{{ global_ci_type }}.yml"
