---
# arguments spec file for redhatci.ocp.test_report_send role
argument_specs:
  main:
    short_description: Main entry point for the redhatci.ocp.test_report_send role
    description: |
      This is the main entrypoint for the role `redhatci.ocp.test_report_send`.
      The role constructs a single event made of:

      * tests report data: `trs_report_path`
      * runtime metadata, either:
          * `trs_metadata_path`
          * CI specific metadata collected from environment variables
      This event is sent to the collector (currently only splunk is supported).
    author:
      - Max Kovgan
    options:
      trs_report_path:
        type: str
        required: false
        description: |
          Test report JSON file to send.
          Merged into the event under 'test' attribute.
          For full report syntax see (TBD).

      trs_metadata_path:
        type: str
        required: false
        default: ""
        description: |
          Event metadata JSON file to send.
          Merged into the event 'metadata' attribute.
          Useful to mark special datasets during development.
          If set to be empty or the file is missing, it is ignored.

      trs_collector_url:
        type: str
        required: true
        description: >
          The URL of collector server (Splunk).

      trs_collector_auth_token:
        type: str
        required: false
        description: >
          Collector auth token string for Bearer Token HTTP Authentication.

      trs_collector_target:
        type: str
        required: true
        description: >
          Collector Target/Channel/Topic/Id

      trs_collector_type:
        type: str
        required: false
        default: splunk
        description: >
          Collector type (currently only `splunk` is supported).

      trs_supported_collector_types:
        type: list
        elements: str
        required: false
        default:
          - splunk
        description: |
          Supported collectors types list.

      trs_supported_ci_systems:
        type: list
        elements: str
        required: false
        default:
          - dci
          - jenkins
          - prow
        description: |
          Supported CI systems list.

      trs_collector_auth_headers:
        type: dict
        required: false
        default: {}
        description: |
          Collector request HTTP headers for HTTP Authentication.

      trs_ci_detect_skip:
        type: bool
        required: false
        default: false
        description: |
          Skip auto-detection of CI system (mainly mor dev).
