# SPDX-License-Identifier: Apache-2.0
---
# tasks file main.yml for role redhatci.ocp.junit2json

- name: Validate some variables
  ansible.builtin.assert:
    that: "{{ condition }}"
  loop:
    - global_reports_path_patterns | length > 0
    - junit2json_input_reports_list | length > 0
    - junit2json_output_dir | length > 0
  loop_control:
    loop_var: condition

- name: Initialize input reports variable
  ansible.builtin.debug:
    msg: "junit2json_input_reports_list: {{ junit2json_input_reports_list }}"

- name: Initialize reports variable
  ansible.builtin.set_fact:
    junit2json_reports_list: []

- name: Expand the input list to list of existing files
  ansible.builtin.include_tasks:
    file: expand.yml
  loop: "{{ junit2json_input_reports_list }}"
  loop_control:
    loop_var: path_item

- name: "Merge JUnit XML reports into single file [`junit2json_do_merge: true`]"
  ansible.builtin.include_tasks:
    file: merge.yml
  when:
    - junit2json_do_merge
    - _junit2json_found_xml_reports.matched > 0

- name: Convert XML to JSON
  ansible.builtin.include_tasks:
    file: convert.yml
  loop: "{{ junit2json_reports_list }}"
  loop_control:
    loop_var: xml_report
  when:
    - junit2json_reports_list | length > 0
