---
# tasks file for redhatci.ocp.junit2json
# task list: convert.yml consolidates multiple XMLs into 1 and converts it into JSoN

# - name: Create helper empty list for XML data and filename
#   ansible.builtin.set_fact:
#     junit2json_reports_list: []

- name: Generate XML files list
  ansible.builtin.set_fact:
    junit2json_reports_list: "{{ junit2json_reports_list | default([]) + [item] }}"
  loop: "{{ _junit2json_found_reports.files | map(attribute='path') }}"

# debug only:
- name: Print XML reports' filenames data
  ansible.builtin.debug:
    msg:
      - "XML files names: {{ junit2json_reports_list }}"
  when:
    - junit2json_debug is defined
    - junit2json_debug

- name: Merge multiple JUnit XML files into single consolidated report
  ansible.builtin.shell:
    cmd: |
      junitparser merge "{{ junit2json_reports_list | join('" "') }}" -
  register: _junit2json_merged_xml
  changed_when:
    - true
  failed_when:
    - _junit2json_merged_xml.rc != 0

- name: Write merge resulting file
  ansible.builtin.copy:
    content: "{{ _junit2json_merged_xml.stdout }}"
    dest: "{{ junit2json_result_xml_path }}" # so that our findings don't find it
    mode: '0644'
  when:
    - _junit2json_merged_xml.stdout | length > 10

- name: Update the xml files list for conversion
  ansible.builtin.set_fact:
    junit2json_xml_reports: [junit2json_result_xml_path]
