---

- name: Set is_ci attribute
  ansible.builtin.set_fact:
    trs_ci: "{{ trs_ci | combine({'is_ci': true}) }}"
  when:
    - lookup("env", "CI") | lower == "true"

- name: Update trs_ci.type for {{ trs_ci_system }}
  ansible.builtin.set_fact:
    trs_ci: "{{ trs_ci | combine({'type': trs_ci_system}) }}"

- name: Update trs_ci.url for {{ trs_ci_system }}
  ansible.builtin.set_fact:
    trs_ci: "{{ trs_ci | combine({'url': lookup('env', 'JENKINS_URL')}) }}"

- name: Update trs_ci.job for {{ trs_ci_system }}
  ansible.builtin.set_fact:
    trs_ci: "{{ trs_ci | combine({'job': lookup('env', 'JOB_NAME')}) }}"
  when:
    - lookup("env", "JOB_URL") | length > 0
